myblog:
  build: .
  ports:
    - "80:80"
  links:
    - redis:redis
    - mysql:mysql
  env_file: .env
  #  command: /myblog/manage.py runserver 0.0.0.0:8000

mysql:
  image: daocloud.io/mysql:latest
  environment:
    - MYSQL_DATABASE=myblog
    - MYSQL_ROOT_PASSWORD=mysql
  ports:
    - "3306:3306"

redis:
  image: daocloud.io/redis:latest
  ports:
    - "6379:6379"
